### ISSUE TITLE
Enemy attack animations slightly too fast at high framerates?

### ISSUE THREAD

**Issue by kevinfoley** [luciusDXL/TheForceEngine#286] opened 2023-07-05 17:04 UTC
When playing Dark Forces in TFE, one thing I notice is that the attack animations for some enemies are very fast, giving those enemies a 'twitchy' look. I haven't played through the whole game yet, but so far this is particularly noticeable for the stormtrooper and commando. Not all enemies are affected; for example, the attack animation for the Grans ('Ree-Yees') looks fine.

If I play the Steam version (DOSBox) with the default cycle settings, the framerate for the game is low by modern standards (I would guess 20 - 30 fps?). At this lower framerate, the attack animations for the stormtrooper and commando look fine. However, if I use Ctrl-F12 to bump up the cycles, the framerate increases, and those problematic attack animations start looking the same as in TFE (too fast and twitchy).

So it does seem that this is a problem with the original game, but only when the framerate is high. I don't know what kinds of framerates were attainable on 1995 hardware, but it's possible the developers didn't time the original animations as carefully as they could have because it wasn't a noticeable problem at the time.

Is it worth adding an option to tweak the timing of some of these animations so they look better at high framerates?

**Comment by luciusDXL** [comment] 2023-08-03 00:16
Perhaps. At some point I need to deal with general frame interpolation - since the game uses quantized time (ticks), which can lead to micro stutter. Probably not something I want to tackle until I see how time is handled in Outlaws, but perhaps when I do I can look at the root cause of the animation quirkiness.

**Comment by luciusDXL** [comment] 2024-08-17 19:23
Thinking about it, I'm unlikely to change the game code to "deal" with this. So I'm going to close this. But once interpolation is implemented, if there is still an issue we can revisit it then.

**Closed by luciusDXL** 2024-08-17 19:23 UTC
