### ISSUE TITLE
How do i install or compile this on Linux? 

### ISSUE THREAD

**Issue by dziadulewicz** [luciusDXL/TheForceEngine#251] opened 2023-02-17 21:04 UTC
Sorry, i created this account for asking for help because i'd really like to try this and play Dark Forces.

There was no executable file so i tried the compiling but it doesn't work:

`git clone https://github.com/luciusDXL/TheForceEngine.git
Cloning into 'TheForceEngine'...
remote: Enumerating objects: 19062, done.
remote: Counting objects: 100% (661/661), done.
remote: Compressing objects: 100% (390/390), done.
remote: Total 19062 (delta 397), reused 484 (delta 264), pack-reused 18401
Receiving objects: 100% (19062/19062), 48.32 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (14354/14354), done.
cd TheForceEngine
~/TheForceEngine $ mkdir build
~/TheForceEngine $ cd build

~/TheForceEngine/build $ cmake ..
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang - broken
CMake Error at /usr/share/cmake-3.24/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/user/TheForceEngine/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_772f0/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_772f0.dir/build.make CMakeFiles/cmTC_772f0.dir/build
    gmake[1]: Entering directory '/home/user/TheForceEngine/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_772f0.dir/testCCompiler.c.o
    /usr/bin/clang    -MD -MT CMakeFiles/cmTC_772f0.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_772f0.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_772f0.dir/testCCompiler.c.o -c /home/user/TheForceEngine/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_772f0
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_772f0.dir/link.txt --verbose=1
    /usr/bin/clang CMakeFiles/cmTC_772f0.dir/testCCompiler.c.o -o cmTC_772f0 
    ld.lld: error: cannot open crtbeginS.o: No such file or directory
    ld.lld: error: unable to find library -lgcc
    ld.lld: error: unable to find library -lgcc
    ld.lld: error: cannot open crtendS.o: No such file or directory
    clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_772f0.dir/build.make:100: cmTC_772f0] Error 1
    gmake[1]: Leaving directory '/home/user/TheForceEngine/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_772f0/fast] Error 2
    
CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)

-- Configuring incomplete, errors occurred!
See also "/home/user/TheForceEngine/build/CMakeFiles/CMakeOutput.log".
See also "/home/user/TheForceEngine/build/CMakeFiles/CMakeError.log".`

**Comment by mlauss2** [comment] 2023-02-18 08:06
Can your toolchain build other source packages?  It looks like it's missing a few things...

**Comment by JoshuaPettus** [comment] 2023-02-21 01:22
if you are using clang as a compiler, I would also look into the clang linker

**Comment by dziadulewicz** [comment] 2023-04-25 11:52
> Your linker (lld) seems to be misconfigured; your toolchain cannot even build a simple test program. This is not an issue with TFE, but your distro/toolchain setup.

Ok. I was wondering would the case be the same if this program was packaged as a Flatpak or a Snap with everything needed in it?

**Comment by VannFanel** [comment] 2023-05-24 15:45
I hope this is the right thread to tack info on, for other Linux newbies like myself. I just got this compiled on Mint 21 and wanted to share how I managed to circumvent my build issues (with thanks to a tip from [ceccopierangiolieugenio](https://github.com/ceccopierangiolieugenio) in another post). I don't know if this is useful to add to the build instructions on the main page, but using:
- libdevil-dev for DevIL
- librtaudio-dev for RTAudio
- librtmidi-dev for RTMidi
- libglew-dev for GLEW (double check the correct version)
from my package manager helped get me mostly over the hurdle for build dependencies. I did have to build SDL2 2.26.5 from source and install it, but after that, TFE worked as intended! I've been waiting about 5 months to try something different to get a working build! The only other mistake I was making that seems important is that I didn't realize building in the source folder was a huge mistake. Adding "mkdir build; cd build" to my process seemed to be another huge revelation. May the Dark Forces be with you all!

**Comment by VannFanel** [comment] 2023-05-25 16:35
More specifically to [dziadulewicz](https://github.com/dziadulewicz), I ran into similar problems when I went to compile this again on my laptop for a trip and ran into a different problem than on my desktop. If you're on a Debian-based distro, you can try installing build-essentials through your package manager (I'm not sure for other distros what this could be called or if it even exists). That fixed my cmake not finding the designated compiler and then I was able to complete the build, despite seemingly having all the other reqs.

**Comment by luciusDXL** [comment] 2023-09-27 21:32
There is already an issue regarding better Linux compilation instructions, so I'm going to close this issue.

**Closed by luciusDXL** 2023-09-27 21:32 UTC
