### ISSUE TITLE
Enable Subtitles Only still show up the Captions !

### ISSUE THREAD

**Issue by TP555** [luciusDXL/TheForceEngine#296] opened 2023-08-01 08:43 UTC
Hi

Only Subtitles Enable does still show up the Captions.
is the same issue for Cutscenes and Gameplay  !

Cheers !

**Comment by DamnBriggsy** [comment] 2023-08-01 16:35
I think the issue is what I came to report myself, at least some SFX captions are showing up when you have dialog subtitles enabled, but SFX captions disabled. I did not extensively test this, but in the first level I was seeing SFX captions for doors when I had only dialog enabled.

**Comment by TP555** [comment] 2023-08-01 17:46
@DamnBriggsy

Yes exactly this issue  !
Not only Some , in Cutscenes was it all SFX !

https://www.youtube.com/watch?v=e_zQEdAI4UM  like 2:58  !

Cheers !

**Comment by luciusDXL** [comment] 2023-08-02 01:22
Fixed with version 1.09.41

**Closed by luciusDXL** 2023-08-02 01:22 UTC
