### ISSUE TITLE
Clicking the "Reset midi output" button the sound settings 7-8 times results in a segfault.

### ISSUE THREAD

**Issue by MIvanchev** [luciusDXL/TheForceEngine#404] opened 2024-04-20 08:09 UTC
Observed on Linux. Go to the sound settings, start clicking "Reset midi output". The game will crash with a segfault. Sadly compiling the Debug configuration doesn't include debug symbols somehow so gdb tells me nothing about the cause.

**Comment by luciusDXL** [comment] 2024-04-25 02:57
Interesting. I was not able to reproduce on Windows, so maybe this is a Linux specific issue.

**Comment by MIvanchev** [comment] 2024-04-25 06:58
Hey, I managed to extract a backtrace:

```
[New Thread 0x7fffcc8566c0 (LWP 6346)]
[Startup] TFE_Polygon::init
[Startup] TFE_Image::init
[Startup] TFE_FrontEndUI::init
[MemoryRegion] Allocated new memory block in region 'game' - new size is 1 blocks, total size is '8388608'
[MemoryRegion] Allocated new memory block in region 'level' - new size is 1 blocks, total size is '8388608'
[Progam Flow] The Force Engine Game Loop Started

Thread 11 "SDLAudioP2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcd0576c0 (LWP 6344)]
0x00005555555a5c9b in OPL3_Generate4Ch (chip=chip@entry=0x55555578b440 <TFE_Audio::s_fmChip>, buf4=buf4@entry=0x55555578c68c <TFE_Audio::s_fmChip+4684>)
    at /builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/MidiSynth/opl3.c:1138
warning: 1138	/builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/MidiSynth/opl3.c: No such file or directory
(gdb) bt
#0  0x00005555555a5c9b in OPL3_Generate4Ch (chip=chip@entry=0x55555578b440 <TFE_Audio::s_fmChip>, buf4=buf4@entry=0x55555578c68c <TFE_Audio::s_fmChip+4684>)
    at /builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/MidiSynth/opl3.c:1138
#1  0x00005555555a6031 in OPL3_Generate4ChResampled (chip=0x55555578b440 <TFE_Audio::s_fmChip>, buf4=buf4@entry=0x7fffcd056d60)
    at /builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/MidiSynth/opl3.c:1271
#2  0x00005555555a6100 in OPL3_GenerateResampled (chip=<optimized out>, buf=0x7fffcd056d84) at /builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/MidiSynth/opl3.c:1288
#3  0x00005555555a2df7 in TFE_Audio::Fm4Opl3Device::render (sampleCount=<optimized out>, buffer=0x7fffbc002838, this=<optimized out>)
    at /builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/MidiSynth/fm4Opl3Device.cpp:177
#4  TFE_Audio::Fm4Opl3Device::render (this=0x555557063d00, buffer=<optimized out>, sampleCount=<optimized out>)
    at /builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/MidiSynth/fm4Opl3Device.cpp:170
#5  0x00005555555aed8c in TFE_MidiPlayer::synthesizeMidi (buffer=0x55555705f490, stereoSampleCount=1024, updateBuffer=true)
    at /builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/midiPlayer.cpp:290
#6  0x00005555555adf28 in TFE_Audio::audioCallback (userData=<optimized out>, outputBuffer=<optimized out>, bufsize=<optimized out>)
    at /builddir/TheForceEngine-1.09.540/TheForceEngine/TFE_Audio/audioSystem.cpp:563
#7  0x00007ffff7d21401 in ?? () from /usr/lib/libSDL2-2.0.so.0
#8  0x00007ffff7d92c05 in ?? () from /usr/lib/libSDL2-2.0.so.0
#9  0x00007ffff7e45e69 in ?? () from /usr/lib/libSDL2-2.0.so.0
#10 0x00007ffff76a2962 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#11 0x00007ffff771db08 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by luciusDXL** [comment] 2024-04-25 18:46
Thanks, I will see what I can figure out.

**Comment by mlauss2** [comment] 2024-07-22 18:00
Still cannot reproduce this, with or without a game running in the background. SDL2-2.30.3
I'm leaning towards an issue on your system perhaps? compiler and/or SDL issue?

**Comment by MIvanchev** [comment] 2024-07-22 18:42
Let me check it again!

**Comment by luciusDXL** [comment] 2024-08-17 18:59
I cannot reproduce this issue with the latest code, so I'm closing for now. If the issue comes up again, feel free to re-open or open another issue.

**Closed by luciusDXL** 2024-08-17 18:59 UTC
