### ISSUE TITLE
Disable frame copy when not recording

### ISSUE THREAD

**Issue by Gerwin2k** [luciusDXL/TheForceEngine#363] opened 2023-10-18 14:16 UTC
Beforehand: My understanding of this functionality is limited and it is possible that what I am suggesting is not feasible.

I have one older system with a Radeon HD 7750 and a driver from 2015. I was investigating why it did not lock to 60 FPS VSync, instead it clearly stutters: floats around 60 FPS but always 5 to 20 frames away from the 60.  
Finally arrived at the function below, and in particular the two lines starting with void* and memcpy. When I comment out these two  lines the system gives a perfect 60 FPS + VSync, HD true-color GPU + bloom.  Savegame preview screenshots remain functional. **Would it be useful to guard this frame copy to only enable when recording?**

TFE_RenderBackend/Win32OpenGL/screenCapture.cpp
function void ScreenCapture::update(bool flush)

```
else if (flush || m_frame > (m_captures[m_captureHead].frame + CAPTURE_FRAME_DELAY))
{
	// Copy from staging data to read buffer [readBuffer].
	glBindBuffer(GL_PIXEL_PACK_BUFFER, m_stagingBuffers[m_captures[m_captureHead].bufferIndex]);
	void* imageData = glMapBufferRange(GL_PIXEL_PACK_BUFFER, 0, m_captures[m_captureHead].imageData.size(), GL_MAP_READ_BIT);
	memcpy(m_captures[m_captureHead].imageData.data(), imageData, m_captures[m_captureHead].imageData.size());
	glUnmapBuffer(GL_PIXEL_PACK_BUFFER);

	// Cleanup.
	glBindBuffer(GL_PIXEL_PACK_BUFFER, 0);
	CHECK_GL_ERROR

	popHead = true;
}
```

**Comment by Gerwin2k** [comment] 2023-10-19 23:07
@mlauss2 
Thanks for looking into this. 
I tried your above modification of the header, instead of my earlier modification. I do see a difference in that the frame-rate is more stable, but it is around 50 FPS, not 60. 
When I then add my earlier modification on top, I get the smooth 60 FPS again. Seemingly your modification does not completely prevent the copying of the frame there. 

( my testing codebase is 1.09.500 from last month )

**Comment by luciusDXL** [comment] 2023-10-20 18:07
It should not be capturing/copying frames when the recording is not enabled. So I will fix this on my end. Thanks for bringing it up. :)

**Comment by luciusDXL** [comment] 2023-10-20 18:12
Yeah, you are correct @Gerwin2k and @mlauss2 - it was uninitialized members. I will push a fix, thanks. :)

**Comment by luciusDXL** [comment] 2023-10-21 17:11
Better consistency between compilers is probably good. But I agree that it can hide initialization issues. But overall, it will probably be more good than bad.

**Comment by Gerwin2k** [comment] 2023-10-21 21:49
Just a preliminary reply about @mlauss suspicion "there's more missing initializers"
I am on GCC v10.3 currently so that v12 feature is not yet available in my workspace.
Attached a build log with four sections.
SECTION 1 - small summary of Wmaybe-uninitialized of full build log section 4 below
SECTION 2 - partial build log whilst enabling lucious recent fix in screenCapture.h
SECTION 3 - partial build log whilst reverting lucious recent fix in screenCapture.h
SECTION 4 - Full build log GCC 10.3 / TheForceEngine v1.09.500

Difference between section 2 and 3 was actually logged partially as warnings with subject "-Wreorder"

If the game is still wasting effort somewhere then maybe make a profiler build with gprof or similar? 

[buildlog-4-sections.txt](https://github.com/luciusDXL/TheForceEngine/files/13061887/buildlog-4-sections.txt)

**Comment by Gerwin2k** [comment] 2023-10-21 22:50
>If the game is still wasting effort somewhere then maybe make a profiler build with gprof or similar?
Attached the result of that, after playing level 1. I cannot quickly see anything inappropriate in the top of the listing.
[TheForceEngineDbg-GProf-Win32.zip](https://github.com/luciusDXL/TheForceEngine/files/13061969/TheForceEngineDbg-GProf-Win32.zip)

**Comment by Gerwin2k** [comment] 2023-10-22 15:47
Can second that midi player dynamic, I switched back to system midi yesterday, since I noticed the SF2-midi thread takes one core and keeps it at 100% usage.

In general the dynamics can change a lot with different build options and settings. For example in the snippet below it has a Linux CPU release method, but WIN32 looked like a stub. function sleep lowercase is called with the strange argument 0 by the frame limiter. I changed it to use SDL_Delay as shown for WIN32. This reduces overall combined CPU usage from 50% to 30%. But only when the frame limiter actually kicks in. VSync enable complicates that. VSync at 60 with frame limiter at 63 gives the mentioned benefit. 

TFE_System\system.cpp
```
#ifdef _WIN32
	void sleep(u32 sleepDeltaMS)
	{
		//Sleep(sleepDeltaMS);
		if (sleepDeltaMS==0) SDL_Delay(1); // GB 2023
		else SDL_Delay(sleepDeltaMS);      // GB 2023
	}
#elif defined __linux__
	void sleep(u32 sleepDeltaMS)
	{
		struct timespec ts = {0, 0};
		while (sleepDeltaMS >= 1000) {
			ts.tv_sec += 1;
			sleepDeltaMS -= 1000;
		}
		ts.tv_nsec = sleepDeltaMS * 1000000;
		nanosleep(&ts, NULL);
	}
#endif
```

**Comment by Gerwin2k** [comment] 2023-10-22 21:09
> It's been a while, but I think sleep(0) on windows causes the current process to just be put at the back of scheduler runqueue, i.e. voluntary yielding the cpu to other processes (if there are any to run). Which is a bit pointless IMO.
> 
> We should replace the sleep() function with calls to SDL_Delay() everywhere, gets at least rid of another #ifdef.

https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep
"A value of zero causes the thread to relinquish the remainder of its time slice to any other thread that is ready to run. If there are no other threads ready to run, the function returns immediately, and the thread continues execution."

So as it was, it often returns immediately. With >1 parameter it is similar to SDL_Delay() in theory and practice.

I don't have a template ready on how to implement SDL_Delay() optimally in both VSync and Frame limiter mode. Besides what I already posted earlier. It has to be at the right place in the code, like around SDL_GL_SwapWindow.  In some cases one has to pass a calculated time as parameter.

**Comment by luciusDXL** [comment] 2023-10-24 17:27
The point of the sleep in the frame limiter is simply to return control to the OS regularly (to keep things responsive). That is why 0 is specified, it is meant to return immediately if nothing else needs to happen. The idea is to reduce the frames queued for the GPU, rather than reducing CPU load. A longer term sleep/delay can be used if that is the goal, but then the issue is that you are more likely to delay for too long and reduce the frame rate.

**Comment by luciusDXL** [comment] 2023-10-24 17:30
Anyway, the original problem should be solved, so I will close this for now. Thanks for bringing up the initialization issues. 👍

**Closed by luciusDXL** 2023-10-24 17:30 UTC
