### ISSUE TITLE
Free Kelly Crash

### ISSUE THREAD

**Issue by DatMaxNub** [luciusDXL/TheForceEngine#320] opened 2023-09-11 04:49 UTC
Version: 1.09.410-7-gdead22da
Game: Dark Forces
Mod: Free Kelly
[crashdump.zip](https://github.com/luciusDXL/TheForceEngine/files/12572314/crashdump.zip)

Had a random crash around these coordinates in game. Was fighting Probe Droids at the time

![cords](https://github.com/luciusDXL/TheForceEngine/assets/19301383/ff7f4e4c-196d-4ff2-90a9-4284624a129f)

**Comment by luciusDXL** [comment] 2023-09-27 22:53
This was most likely caused by a memory write bug that was recently fixed. So I'm closing unless it comes up again.

**Closed by luciusDXL** 2023-09-27 22:53 UTC
