### ISSUE TITLE
Gromas’ red fog disappears

### ISSUE THREAD

**Issue by JakeSmarter** [luciusDXL/TheForceEngine#434] opened 2024-07-26 22:23 UTC
Linux Flathub v1.10.000-28-ge19bcde1+

Every shot fired (except the fist, the thermal detonator, and the mine) on Gromas makes the red fog disappear briefly. I am not sure this is coherent with the original game.

**Comment by mlauss2** [comment] 2024-07-27 10:23
I think the original DOS version does that too.  Just watch some old youtube videos.

**Comment by luciusDXL** [comment] 2024-07-29 21:00
No, it also happens in DosBox - it is the way the colormap code works (it is caused by the extra fogging around the camera you see in Gromas, normally the weapon fire is range limited).

DosBox - normal
![image](https://github.com/user-attachments/assets/fd4efe99-a72b-4e17-a765-824a19e84a53)

DoxBox - lit up. Notice that even the cliffs in the background are lighting up.
![image](https://github.com/user-attachments/assets/e224565d-21f0-4570-8f8f-3a66b4bf4a06)

**Comment by luciusDXL** [comment] 2024-07-29 21:00
This is not a TFE bug, but the way the original renderer works.

**Comment by luciusDXL** [comment] 2024-07-29 21:01
This is not a TFE bug, but the way the original renderer works. So I'm closing the issue.

**Closed by luciusDXL** 2024-07-29 21:01 UTC

**Comment by TP555** [comment] 2024-09-04 15:45
Hi

@JakeSmarter

Thats not realy a fog Effect, this will more Simulate a Heat/Haze Effect, which is more inside the Buildings.

Here are a Footage, and which issues produce this Effect also,

And this is real Gameplay from 1995!
https://www.youtube.com/watch?v=qtDCk8T1NkI 1:58

Cheers!
