### ISSUE TITLE
Linux: Lowercased files can be found but not LFD

### ISSUE THREAD

**Issue by MartinHowe426** [luciusDXL/TheForceEngine#252] opened 2023-02-18 17:42 UTC
Original game files zipped from old clean DOS install.
All objects renamed to lower case.

Issue: the engine can find all the _files_ when lower case named, but not the LFD _directory_. If that is left as uppercase named everything works. If **LFD** is renamed to **lfd** the game crashes.

Sure, it's not the end of the world, but if the game is going to look for official game data _files_ ignoring filename case, surely it should do the same for _directories_ too?

**Comment by mlauss2** [comment] 2023-02-19 07:34
My first reaction is:  Why would you do that?  Just use the original file cases from shipped original/Steam/Gog.
I think I know what the issue is: when the engine requests a filename (LFD/FiLeNaM.lFd) only the FiLeNaM.lFd part is checked for other-case files.   Let me think about how to solve this...

**Comment by MartinHowe426** [comment] 2023-02-19 10:50
Thanks for taking an interest and not just saying 'no' and closing it; I realised this was likely to be an edge case from your PoV.

It's not difficult to work around but the reason I naively expected it to work is that other source ports for old DOS games (e.g., EDuke32) mostly handle this on Linux; but if it's going to be too messy to do in the context of how TFE works internally, then fair enough, I get it's not a priority and am grateful that TFE can run natively on Linux _at all._

I got around it by having a non-empty post-install function, in my DF install script, which creates a symlink called LFD -> lfd.

For my scripts than manage playing and installing/uninstalling the mess of old games with their differing file layouts and quirks, base files, and source ports, it's a lot simpler with standardised file naming conventions; whoever said 'convention over configuration' should be given a medal :)

Also, looking at uppercase file names is quite ugly; IT'S CALLED "SHOUTING" FOR A REASON :)

Plus, I come from a time when by convention on UNIX ( yes, I'm 'afraid to use spaces in filenames' old :) ) most people used lowercase filenames for everything to avoid problems on a case sensitive filesystem. Sadly, modern Unices and Linux proliferated mixed case filenames in system files, making life a lot more difficult for everyone but end users that don't write their own scripts.

**Comment by mlauss2** [comment] 2023-02-19 11:11
I'll try to whip something up, it's super easy to reproduce anyway, so why not fix it :)

**Comment by mlauss2** [comment] 2023-02-19 12:10
Can you please test this patch on top of master?  It works with the "LFD" directory renamed to "lfd" for me. But I haven't tested anything else (mods/ instead of Mods/ , ...)

```diff
--- a/TheForceEngine/TFE_FileSystem/fileutil-posix.cpp
+++ b/TheForceEngine/TFE_FileSystem/fileutil-posix.cpp
@@ -15,6 +15,8 @@
 // implement TFE FileUtil for Linux and compatibles.
 namespace FileUtil
 {
+       static char *findFileObjectNoCase(const char *filename, bool objisdir);
+
        void readDirectory(const char *dir, const char *ext, FileList& fileList)
        {
                char buf[PATH_MAX];
@@ -221,14 +223,21 @@ namespace FileUtil
                }
        }
 
-       bool directoryExits(const char *path)
+       bool directoryExits(const char *path, char *outPath)
        {
-               struct stat st;
-               int ret = stat(path, &st);
-               if (ret != 0)
+               char *ret;
+
+               fprintf(stderr, "dirExits: %s\n", path);
+               ret = findFileObjectNoCase(path, true);
+               fprintf(stderr, "dirExits(%s) = %s\n", path, ret);
+               if (ret == NULL)
                        return false;
-
-               return (st.st_mode & S_IFDIR) != 0;
+
+               // replace input with found path
+               if (outPath)
+                       snprintf(outPath, TFE_MAX_PATH, "%s/", ret);
+               free(ret);
+               return true;
        }
 
        bool exists(const char *path)
@@ -237,10 +246,13 @@ namespace FileUtil
        }
 
        // Linux filesystems are case-sensitive; try to open the
-       // base directory and find a file that has the same name
+       // base directory and find a file/directory that has the same name
        // with different case.
        // Caller MUST free the pointer returned by this function!
-       char *findFileNoCase(const char *filename)
+       // Input: full path to file or dir: /abs/path/to/object
+       // This function will try to find "object" with differently cased name
+       // in path "/abs/path/to/".
+       static char *findFileObjectNoCase(const char *filename, bool objisdir)
        {
                char *fncopy, *dn, *fn;
                char *result = NULL;
@@ -259,7 +271,7 @@ namespace FileUtil
                memset(fncopy, 0, ol + ol + 2);
                strncpy(fncopy, filename, ol);
                strncpy(fncopy + ol + 1, filename, ol);
-
+
                dn = dirname(fncopy);
                fn = basename(fncopy + ol +1);
 
@@ -281,8 +293,15 @@ namespace FileUtil
                        memset(buf, 0, PATH_MAX);
                        snprintf(buf, PATH_MAX - 2, "%s/%s", dn, de->d_name);
                        ret = stat(buf, &st);
-                       if ((ret != 0) || (!S_ISREG(st.st_mode)))
+                       if (ret != 0)
                                continue;
+                       if (objisdir) {
+                               if (!S_ISDIR(st.st_mode))
+                                       continue;
+                       } else {
+                               if (!S_ISREG(st.st_mode))
+                                       continue;
+                       }
 
                        nfl = strlen(de->d_name);
                        if (nfl != fl)
@@ -304,6 +323,11 @@ namespace FileUtil
                return result;
        }
 
+       char *findFileNoCase(const char *filename)
+       {
+               return findFileObjectNoCase(filename, false);
+       }
+
        bool existsNoCase(const char *filename)
        {
                char *fn2 = findFileNoCase(filename);
diff --git a/TheForceEngine/TFE_FileSystem/fileutil.cpp b/TheForceEngine/TFE_FileSystem/fileutil.cpp
index 5f9dc137..49183f69 100644
--- a/TheForceEngine/TFE_FileSystem/fileutil.cpp
+++ b/TheForceEngine/TFE_FileSystem/fileutil.cpp
@@ -221,7 +221,7 @@ namespace FileUtil
                DeleteFile(srcFile);
        }
 
-       bool directoryExits(const char* path)
+       bool directoryExits(const char* path, char* outPath)
        {
                DWORD attr = GetFileAttributesA(path);
                if (GetFileAttributesA(path) == INVALID_FILE_ATTRIBUTES) { return false; }
diff --git a/TheForceEngine/TFE_FileSystem/fileutil.h b/TheForceEngine/TFE_FileSystem/fileutil.h
index 54f7738f..237602c8 100644
--- a/TheForceEngine/TFE_FileSystem/fileutil.h
+++ b/TheForceEngine/TFE_FileSystem/fileutil.h
@@ -25,7 +25,7 @@ namespace FileUtil
 
        bool exists(const char* path);
        bool existsNoCase(const char* path);
-       bool directoryExits(const char* path);
+       bool directoryExits(const char* path, char* outPath = nullptr);
        u64  getModifiedTime(const char* path);
 
        void fixupPath(char* path);
diff --git a/TheForceEngine/TFE_FileSystem/paths-posix.cpp b/TheForceEngine/TFE_FileSystem/paths-posix.cpp
index d1cb1196..bc5b82e1 100644
--- a/TheForceEngine/TFE_FileSystem/paths-posix.cpp
+++ b/TheForceEngine/TFE_FileSystem/paths-posix.cpp
@@ -172,34 +172,38 @@ namespace TFE_Paths
 
        void addSearchPath(const char *fullPath)
        {
-               if (!FileUtil::directoryExits(fullPath))
+               char workpath[TFE_MAX_PATH];
+
+               if (!FileUtil::directoryExits(fullPath, workpath))
                        return;
 
                for (auto it = s_searchPaths.begin(); it != s_searchPaths.end(); it++)
                {
                        // If the path already exists, then don't add it again.
-                       if (!strcasecmp(it->c_str(), fullPath))
+                       if (!strcasecmp(it->c_str(), workpath))
                        {
                                return;
                        }
                }
-               s_searchPaths.push_back(fullPath);
+               s_searchPaths.push_back(workpath);
        }
 
        void addSearchPathToHead(const char *fullPath)
        {
-               if (!FileUtil::directoryExits(fullPath))
+               char workpath[TFE_MAX_PATH];
+
+               if (!FileUtil::directoryExits(fullPath, workpath))
                        return;
 
                for (auto it = s_searchPaths.begin(); it != s_searchPaths.end(); it++)
                {
                        // If the path already exists, then don't add it again.
-                       if (!strcasecmp(it->c_str(), fullPath))
+                       if (!strcasecmp(it->c_str(), workpath))
                        {
                                return;
                        }
                }
-               s_searchPaths.push_front(fullPath);
+               s_searchPaths.push_front(workpath);
        }
 
        void clearSearchPaths(void)


```

**Comment by mlauss2** [comment] 2023-02-19 13:16
Should be fixed by #253

**Comment by MartinHowe426** [comment] 2023-02-19 13:19
Thanks; I have tried, but with no success, both with **patch** command and after some Google, **git apply**. Not having used git much beyond downloading sources, it's probably my mistake; so what should I do to apply the patch? Log file below:

```
martin@luna:~/Games/Engines/TFE$ cd TheForceEngine/
martin@luna:~/Games/Engines/TFE/TheForceEngine$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

martin@luna:~/Games/Engines/TFE/TheForceEngine$ git apply ../patch.diff
error: patch failed: TheForceEngine/TFE_FileSystem/fileutil-posix.cpp:15
error: TheForceEngine/TFE_FileSystem/fileutil-posix.cpp: patch does not apply
error: patch failed: TheForceEngine/TFE_FileSystem/fileutil.cpp:221
error: TheForceEngine/TFE_FileSystem/fileutil.cpp: patch does not apply
error: patch failed: TheForceEngine/TFE_FileSystem/fileutil.h:25
error: TheForceEngine/TFE_FileSystem/fileutil.h: patch does not apply
error: patch failed: TheForceEngine/TFE_FileSystem/paths-posix.cpp:172
error: TheForceEngine/TFE_FileSystem/paths-posix.cpp: patch does not apply

martin@luna:~/Games/Engines/TFE/TheForceEngine$ patch -p1 < ../patch.diff
patching file TheForceEngine/TFE_FileSystem/fileutil-posix.cpp
Hunk #1 FAILED at 15.
Hunk #2 FAILED at 221.
Hunk #3 FAILED at 237.
Hunk #4 FAILED at 259.
Hunk #5 FAILED at 281.
Hunk #6 FAILED at 304.
6 out of 6 hunks FAILED -- saving rejects to file TheForceEngine/TFE_FileSystem/fileutil-posix.cpp.rej
patching file TheForceEngine/TFE_FileSystem/fileutil.cpp
Hunk #1 FAILED at 221.
1 out of 1 hunk FAILED -- saving rejects to file TheForceEngine/TFE_FileSystem/fileutil.cpp.rej
patching file TheForceEngine/TFE_FileSystem/fileutil.h
Hunk #1 FAILED at 25.
1 out of 1 hunk FAILED -- saving rejects to file TheForceEngine/TFE_FileSystem/fileutil.h.rej
patching file TheForceEngine/TFE_FileSystem/paths-posix.cpp
Hunk #1 FAILED at 172.
1 out of 1 hunk FAILED -- saving rejects to file TheForceEngine/TFE_FileSystem/paths-posix.cpp.rej
```

**Comment by MartinHowe426** [comment] 2023-02-19 19:59
Since it's waiting for review; then if it's any help, I cloned mlauss2 repo, double checked it has the edits above, built from that; log below :(

```
martin@luna:~/Games/Engines/TFE$ git clone "https://github.com/mlauss2/TheForceEngine.git" "TheForceEngine"
Cloning into 'TheForceEngine'...
remote: Enumerating objects: 18885, done.
remote: Counting objects: 100% (585/585), done.
remote: Compressing objects: 100% (253/253), done.
remote: Total 18885 (delta 369), reused 510 (delta 327), pack-reused 18300
Receiving objects: 100% (18885/18885), 48.17 MiB | 3.20 MiB/s, done.
Resolving deltas: 100% (14264/14264), done.
martin@luna:~/Games/Engines/TFE$

martin@luna:~/Games/Engines/TFE$ cd TheForceEngine

martin@luna:~/Games/Engines/TFE/TheForceEngine$ mkdir build

martin@luna:~/Games/Engines/TFE/TheForceEngine$ cd build

martin@luna:~/Games/Engines/TFE/TheForceEngine/build$ cmake -DCMAKE_BUILD_TYPE=Debug ..
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Checking for module 'rtaudio>=5.2.0'
--   Found rtaudio, version 5.2.0
-- Checking for module 'rtmidi>=5.0.0'
--   Found rtmidi, version 5.0.0
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.20
-- Checking for module 'glew'
--   Found glew, version 2.2.0
-- Checking for module 'IL'
--   Found IL, version 1.7.8
-- Checking for module 'ILU'
--   Found ILU, version 1.7.8
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
-- Found Git: /usr/bin/git (found version "2.34.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/martin/Games/Engines/TFE/TheForceEngine/build
martin@luna:~/Games/Engines/TFE/TheForceEngine/build$

martin@luna:~/Games/Engines/TFE/TheForceEngine/build$ make -j4
    .....
    stuff
    .....
[100%] Linking CXX executable theforceengine
[100%] Built target tfe

martin@luna:~/Games/Engines/TFE/TheForceEngine/build$ ls -l /usr/share/df
lrwxrwxrwx 1 root root 23 Feb 18 21:06 /usr/share/df -> /usr/share/games/df/1.0

martin@luna:~/Games/Engines/TFE/TheForceEngine/build$ ls -l /usr/share/df/
total 31208
-rw-r--r-- 1 root root 14244049 Feb 18 21:06 dark.gob
drwxr-xr-x 2 root root     4096 Feb 18 21:06 lfd
-rw-r--r-- 1 root root     2989 Feb 18 21:06 local.msg
-rw-r--r-- 1 root root  5950117 Feb 18 21:06 sounds.gob
-rw-r--r-- 1 root root  2816419 Feb 18 21:06 sprites.gob
-rw-r--r-- 1 root root  8929232 Feb 18 21:06 textures.gob

martin@luna:~/Games/Engines/TFE/TheForceEngine/build$ ./theforceengine
[Main] The Force Engine
v1.09.100

[Paths] Program Path: "/home/martin/Games/Engines/TFE/TheForceEngine/build/"
[Paths] Program Data: "/home/martin/.local/share/TheForceEngine/"
[Paths] User Documents: "/home/martin/.local/share/TheForceEngine/"
[Paths] Source Data: ""
    ....
    I click START; it prompts for files, I point it at /usr/share/df
    ....
[Startup] TFE_System::init
[Display] Fullscreen enabled.
[Display] Vertical Sync enabled.
[RenderBackend] OpenGL Device Tier: 3
[Startup] TFE_AudioSystem::init
[Audio] Attempting to initialize Audio System using API 'Linux ALSA'.
[Audio] Default Audio Output ID: 0.
[Audio] Device Count: 10.
[Audio] Device: 'default', ID: 0, Output Channel Count: 32.
[Audio] Device: 'hw:HDA Intel PCH,0', ID: 1, Output Channel Count: 2.
[Audio] Device: 'hw:HDA Intel PCH,1', ID: 2, Output Channel Count: 2.
[Audio] Device: 'hw:HDA Intel PCH,2', ID: 3, Output Channel Count: 0.
[Audio] Device: 'hw:Live! Cam Sync 1080p,0', ID: 4, Output Channel Count: 0.
[Audio] Device: 'hw:HDA NVidia,3', ID: 5, Output Channel Count: 2.
[Audio] Device: 'hw:HDA NVidia,7', ID: 6, Output Channel Count: 8.
[Audio] Device: 'hw:HDA NVidia,8', ID: 7, Output Channel Count: 8.
[Audio] Device: 'hw:HDA NVidia,9', ID: 8, Output Channel Count: 8.
[Audio] Device: 'hw:HDA NVidia,10', ID: 9, Output Channel Count: 8.
[Audio] Audio initialized using API 'Linux ALSA'.
[Audio] Starting up audio stream for device 'default', id 0.
[Startup] TFE_MidiPlayer::init
[Startup] TFE_Polygon::init
[Startup] TFE_Image::init
[Startup] TFE_FrontEndUI::init
[MemoryRegion] Allocated new memory block in region 'game' - new size is 1 blocks, total size is '8388608'
[MemoryRegion] Allocated new memory block in region 'level' - new size is 1 blocks, total size is '8388608'
[Progam Flow] The Force Engine Game Loop Started
[Game] Dark Forces Version: 1.0 (Build 1)
[Warning : DarkForcesMain] Cannot find 'DARKPILO.CFG' at '/usr/share/df/DARKPILO.CFG'. Creating a new file for save data.
[MemoryRegion] Allocated new memory block in region 'Landru' - new size is 1 blocks, total size is '4194304'
[MemoryRegion] Allocated new memory block in region 'Cutscene' - new size is 1 blocks, total size is '8388608'
Segmentation fault (core dumped)

```

**Closed** 2023-02-20 02:43 UTC

**Comment by mlauss2** [comment] 2023-02-20 06:39
If master doesn't work, can you please share the "ls -la" output of your Dark Forces game directory, so I can duplicate your environment more closely.  My main test was "mv LFD lfd" and the patch lucius merged makes tfe work again.

**Comment by MartinHowe426** [comment] 2023-02-20 10:32
No, it all works fine. Thanks very much for your hard work :)
