### ISSUE TITLE
[BUG] "Back to Yavin" map mod (Bugged switch)

### ISSUE THREAD

**Issue by Blackbird88** [luciusDXL/TheForceEngine#178] opened 2022-12-31 19:58 UTC
Back to Yavin
https://df-21.net/downloads/levels.php?view=yavin

If you shoot the switch here, it gets stuck and can't be used second time.
![20221231205544_1](https://user-images.githubusercontent.com/4414625/210154483-c1c0317e-7818-476e-b9b6-be09e9cc5477.jpg)

Save:
[save007.zip](https://github.com/luciusDXL/TheForceEngine/files/10327929/save007.zip)

How it should work:
https://youtu.be/AV0xg4j5Q54?t=302

**Comment by Karjala22** [comment] 2023-01-03 19:11
@luciusDXL The issue is that the trigger reset call is not being processed because TFE is strict in message offsets. In vanilla there is an invalid **message 8** which JEDI happily processes. In TFE it expects the strict **message 3**.

This is a mission issue - not TFE specific. 

Details

**dispatch (4)** switch

`seq
  class: trigger switch1
      entity_mask: *
      event_mask: 272
      message: next_stop  
    client: disp_door
seqend
`

**disp_door** door

The below works in JEDI - although it is invalid - the message 8 stop is wrong. 

`
seq
  class: elevator move_ceiling
      speed: 50
      event_mask: 0
    stop: 0 hold
    stop: 1 0
      message: 1 dispatch(4) m_trigger  
    stop: 8 4
    stop: 7 0
      message: 8 dispatch(4) done  
seqend
`

Setting the done message to the correct offset 3 fixes it.

`
seq
  class: elevator move_ceiling
      speed: 50
      event_mask: 0
    stop: 0 hold
    stop: 1 0
      message: 1 dispatch(4) m_trigger  
    stop: 8 4
    stop: 7 0
      message: 3 dispatch(4) done  
seqend
`

I will patch it

**Comment by luciusDXL** [comment] 2023-01-07 07:37
The root issue has been fixed (so the non-modern version will also work). The fix will be in the next release.

**Comment by luciusDXL** [comment] 2023-01-17 03:17
Fixed in the version 1.02 Release.

**Closed by luciusDXL** 2023-01-17 03:17 UTC
Labels: bug
