### ISSUE TITLE
TFE menus wont respond to input on Linux with multi-monitors

### ISSUE THREAD

**Issue by rktjmp** [luciusDXL/TheForceEngine#276] opened 2023-06-13 23:19 UTC
- Version: v1.09.200
- OS: Linux, nvidia
- WM: Awesome WM, X11
- Monitors: 2

When I run TFE, it appears on my primary monitor (right), but the menu seems to be unresponsive.

I discovered that when moving the mouse cursor to my other monitor (left), the menu buttons start highlighting, so dragging the window over to the left side (basically 0,0 position) made everything work. After starting Dark Forces I can drag the window back to the main monitor and everything is fine (until returning to the TFE menu). This effect occurs in windowed and fullscreen mode.

To really describe the problem: It feels like the menu needs to get the monitor its on, the width of any monitors to the left of it, offset the x position of the cursor by that width. 

To make things complicated, AFAIK my X11 setup has "one screen" that the nvidia driver sub divides into separate monitors.

Keyboard navigation https://github.com/luciusDXL/TheForceEngine/issues/141 might be a simpler (?) work around.

Anyway, maybe if anyone else falls onto this issue, they can just drag their window all the way to the top-left and have it work.

**Comment by luciusDXL** [comment] 2023-07-04 22:14
I think this is related to a display bounds bug that will be fixed in version 1.09.3, so you can retest once that comes out.

**Comment by rktjmp** [comment] 2023-07-05 15:19
Still present as of https://github.com/luciusDXL/TheForceEngine/releases/tag/v1.09.300

**Comment by MindrustUK** [comment] 2023-08-02 09:12
+1 as of commit https://github.com/luciusDXL/TheForceEngine/commit/c565624b2b44fbf987ec33101ba15cbc0814fd13

**Comment by luciusDXL** [comment] 2023-08-03 00:26
Thanks for letting me know the issue is still there.

**Comment by luciusDXL** [comment] 2024-08-17 19:12
Does this issue still exist in version 1.10?

**Comment by rktjmp** [comment] 2024-08-18 05:30
:+1:  The menu bug is not present for me in 1.10 from Arch AUR.

**Closed** 2024-08-19 00:22 UTC
Labels: bug
