### ISSUE TITLE
Stuck in M2 (different behavior than Vanilla)

### ISSUE THREAD

**Issue by Irv1n3** [luciusDXL/TheForceEngine#166] opened 2022-12-24 13:55 UTC
Hi!
If you drop in the water next to the hydro-electric power generator, you can croutch to access to a small area behind it.
When you reach the ending wall, you'll be stuck and can't come back, even by jumping.

I've tested and this issue is not present in Vanilla, you can go back even without jumping.
I don't know if this issue is only present here or if this behavior can be find at another locations in the game but I think it can be an interesting lead!

Thanks!

[Theforceengine Screenshot 2022 12 24 - 14 19 37 88](https://user-images.githubusercontent.com/4195078/209438908-5dc9843c-863e-42eb-8288-63cc9f701063.png)

**Comment by spacekomet** [comment] 2022-12-24 15:20
In my case, when I hold crouch and start jumping I can get out it.
I've noticed similar issue also Mission VIII: Robotics Facility, when you come to the doors at the end of conveyor belt, where you must shoot the red circled switch  to open them. If you come to the doors without opening them, you have difficult time to go back on the conveyor belt., I managed it sporadically jumping and holding shift to run.  Here is the location: https://steamcommunity.com/sharedfiles/filedetails/?id=583646388 

I have no idea how is in the original game though.

**Comment by Irv1n3** [comment] 2022-12-24 16:13
Just tested, indeed jumping while crouching works!
Still something to look into since it's not the same behavior in the original game but thanks for the tip

**Comment by TP555** [comment] 2022-12-24 16:37
Hi

Yes i was stuck there short also , but im not sure , how i could solved it needs diffentive an investigation from Lucius.

**Comment by Q3BFG10K** [comment] 2022-12-26 04:02
I had the same issue in the same place and was able to finally exit by mashing crouch-sprint-jump.

**Comment by Karjala22** [comment] 2022-12-26 16:43
Folks this is identical behavior to Vanilla and not a TFE-specific issue. It has been resolved in the community patch --> https://df-21.net/?post=59

**Comment by Irv1n3** [comment] 2022-12-26 16:59
I don't use this patch but can't reproduce it on vanilla

**Comment by Karjala22** [comment] 2022-12-26 18:47
It 100% happens in vanilla - that's why it was patched in the first place. We've had people abort the mission because they were trapped there (or rather not know about jumping along side the wall). 

https://user-images.githubusercontent.com/78927981/209576206-f5641923-7181-4530-9197-17a9b9019b6c.mp4


Here is a clip.

**Comment by luciusDXL** [comment] 2023-01-06 23:25
I think what is happening here is slightly different behavior in DosBox based on the cycles set. I believe this is working as intended, so I'm going to close this bug.

**Closed by luciusDXL** 2023-01-06 23:25 UTC
Labels: bug
